Repository umccr/orcahouse, pull requests merged in 2025-04, with the labels that each got.

#82 Implemented FASTQ History data mart view
  orcavault/macros/grant_select.sql
  orcavault/models/mart/centre/_schema.yml
  orcavault/models/mart/centre/fastq_history.sql
Labels: enhancement

#84 Improved business vault s3object current model satellite
  orcavault/models/dcl/sat_s3object_current.sql
Labels: enhancement, fix

#85 Improved Centre lims data mart to exclude failed sequencing runs
  orcavault/models/mart/centre/lims.sql
Labels: enhancement, fix

#88 Introduced Virtual Cohort ID
  orcavault/models/mart/centre/fastq.sql
  orcavault/models/mart/centre/fastq_history.sql
Labels: enhancement

#89 Implemented Centre data mart bam inventory
  orcavault/models/mart/centre/_schema.yml
  orcavault/models/mart/centre/bam.sql
Labels: enhancement

#90 Implemented Centre data mart workflow inventory
  orcavault/macros/grant_select.sql
  orcavault/models/mart/centre/_schema.yml
  orcavault/models/mart/centre/workflow.sql
Labels: enhancement

#91 Implemented effsat_library_external_subject on link_library_external_subject
  dev/src/load.sh
  dev/src/ods.sql
  orcavault/models/dcl/effsat_library_external_subject.sql
  orcavault/models/dcl/effsat_schema.yml
  orcavault/models/mart/centre/lims.sql
Labels: enhancement

#93 Fixed mart lims filter on succeeded sequencing runs
  orcavault/models/mart/centre/lims.sql
Labels: fix

#94 Feat/service event ingestion
  .gitignore
  dev/src/psa.sql
  infra/aurora-su/.terraform.lock.hcl
  infra/aurora-su/orcavault_psa.tf
  infra/common/config/data.tf
  infra/common/config/output.tf
  infra/common/config/variables.tf
  infra/service-event-ingestion/.gitignore
  infra/service-event-ingestion/.terraform.lock.hcl
  infra/service-event-ingestion/README.md
  infra/service-event-ingestion/event-ingestion.drawio.svg
  infra/service-event-ingestion/fqr.tf
  infra/service-event-ingestion/lambda/fqr_event_handler/fqr_event_handler.py
  infra/service-event-ingestion/lambda/srm_event_handler/srm_event_handler.py
  infra/service-event-ingestion/main.tf
  infra/service-event-ingestion/srm.tf
  infra/service-event-ingestion/variables.tf
  orcavault/models/psa/sources.yml
Labels: enhancement

#95 Fixed sat_s3object_current model daily cut-over timestamp ranking
  orcavault/models/dcl/sat_s3object_current.sql
Labels: fix

#96 Implemented business vault effectivity satellites on Library to Sample, ExternalSample and Project
  orcavault/models/dcl/effsat_library_external_sample.sql
  orcavault/models/dcl/effsat_library_project.sql
  orcavault/models/dcl/effsat_library_sample.sql
  orcavault/models/dcl/effsat_schema.yml
  orcavault/models/mart/centre/lims.sql
Labels: enhancement

#97 Implemented business vault effectivity satellites on Library to ExternalSubject and Owner
  orcavault/models/dcl/effsat_library_internal_subject.sql
  orcavault/models/dcl/effsat_library_ownership.sql
  orcavault/models/dcl/effsat_schema.yml
  orcavault/models/mart/centre/lims.sql
Labels: enhancement

#98 Implemented OrcaVault Legacy database schema
  dev/Makefile
  dev/src/legacy.sql
  dev/src/load.sh
  dev/src/ods.sql
  orcavault/Makefile
  orcavault/models/dcl/hub_experiment.sql
  orcavault/models/dcl/hub_external_sample.sql
  orcavault/models/dcl/hub_external_subject.sql
  orcavault/models/dcl/hub_internal_subject.sql
  orcavault/models/dcl/hub_library.sql
  orcavault/models/dcl/hub_owner.sql
  orcavault/models/dcl/hub_project.sql
  orcavault/models/dcl/hub_s3object.sql
  orcavault/models/dcl/hub_sample.sql
  orcavault/models/dcl/hub_sequencing_run.sql
  orcavault/models/dcl/hub_workflow_run.sql
  orcavault/models/dcl/link_internal_to_external_sample.sql
  orcavault/models/dcl/link_internal_to_external_subject.sql
  orcavault/models/dcl/link_library_experiment.sql
  orcavault/models/dcl/link_library_external_sample.sql
  orcavault/models/dcl/link_library_external_subject.sql
  orcavault/models/dcl/link_library_internal_subject.sql
  orcavault/models/dcl/link_library_ownership.sql
  orcavault/models/dcl/link_library_project.sql
  orcavault/models/dcl/link_library_sample.sql
  orcavault/models/dcl/link_library_sequencing_run.sql
  orcavault/models/dcl/link_library_workflow_run.sql
  orcavault/models/dcl/link_project_ownership.sql
  orcavault/models/dcl/sat_library_plab.sql
  orcavault/models/dcl/sat_library_plims.sql
  orcavault/models/dcl/sat_library_sequencing_run_plims.sql
  orcavault/models/dcl/sat_s3object_portal.sql
  orcavault/models/dcl/sat_workflow_run_portal.sql
  orcavault/models/legacy/sources.yml
  orcavault/models/ods/sources.yml
Labels: enhancement

#101 Implemented business vault layer satellite model - WorkflowRun
  orcavault/models/dcl/sat_schema.yml
  orcavault/models/dcl/sat_workflow_run.sql
Labels: enhancement

#102 Improved data mart Workflow table
  orcavault/models/mart/centre/workflow.sql
Labels: enhancement

#103 Fixed workflow run state can be null
  orcavault/models/dcl/sat_workflow_run_detail.sql
  orcavault/models/mart/centre/workflow.sql
Labels: fix
