Repository umccr/orcahouse, pull requests merged in 2025-05, with the labels that each got.

#104 Add wfr event handler
  dev/src/psa.sql
  infra/service-event-ingestion/lambda/wfm_event_handler/wfm_event_handler.py
  infra/service-event-ingestion/wfr.tf
  orcavault/models/psa/sources.yml
Labels: enhancement

#106 Improved README
  dev/README.md
  orcavault/README.md
Labels: documentation

#107 Fixed RDS.16 by enabling copy_tags_to_snapshot
  infra/aurora/main.tf
Labels: fix

#108 Implemented orcahouse management instance
  infra/ec2/.terraform.lock.hcl
  infra/ec2/README.md
  infra/ec2/main.tf
Labels: documentation, enhancement

#109 Add DB user for Athena
  infra/athena/.terraform.lock.hcl
  infra/athena/main.tf
  infra/aurora-su/orcahouse_athena.tf
Labels: enhancement

#111 Fix column name mismatch
  dev/src/psa.sql
  orcavault/models/psa/sources.yml
Labels: fix

#112 Fixed dbt hook run operation grant select ro user
  infra/ecs/orcavault-dbt/main.tf
  orcavault/README.md
  orcavault/macros/grant_select.sql
Labels: fix

#113 Removed reference to legacy portal compute security group
  infra/aurora/main.tf
Labels: fix

#114 Improved DCL Library satellite model ranking logic
  orcavault/models/dcl/sat_library_glab.sql
Labels: fix

#115 Feat/lamnda monitoring
  infra/service-event-ingestion/fqr.tf
  infra/service-event-ingestion/monitor.tf
  infra/service-event-ingestion/srm.tf
  infra/service-event-ingestion/wfr.tf
Labels: enhancement

#117 Improved DCL effsat Library Experiment link model incremental logic
  orcavault/models/dcl/effsat_library_experiment.sql
Labels: enhancement, fix

#116 Add Metadata event ingestion
  dev/src/psa.sql
  infra/service-event-ingestion/lambda/mm_lib_event_handler/mm_lib_event_handler.py
  infra/service-event-ingestion/mm.tf
  infra/service-event-ingestion/monitor.tf
  orcavault/models/psa/sources.yml
Labels: enhancement

#120 Improved DCL satellite WorkflowRunComment
  orcavault/models/dcl/sat_schema.yml
  orcavault/models/dcl/sat_workflow_run_comment.sql
Labels: enhancement, fix

#119 Feat: new `lims` graphql endpoint
  .gitignore
  .secrets.baseline
  infra/app-sync/README.md
  infra/app-sync/generate_schema.py
  infra/app-sync/lims/.terraform.lock.hcl
  infra/app-sync/lims/README.md
  infra/app-sync/lims/introspection-schema.json
  infra/app-sync/lims/main.tf
  infra/app-sync/lims/rds-data-config.json
  infra/app-sync/lims/resolvers/list.js
  infra/app-sync/lims/schema.graphql
Labels: enhancement

#123 Add default values for event data to avoid null value issues
  infra/service-event-ingestion/lambda/mm_lib_event_handler/mm_lib_event_handler.py
Labels: fix

#126 str every data element
  infra/service-event-ingestion/lambda/mm_lib_event_handler/mm_lib_event_handler.py
  infra/service-event-ingestion/lambda/srm_llc_event_handler/srm_llc_event_handler.py
  infra/service-event-ingestion/lambda/srm_sc_event_handler/srm_sc_event_handler.py
  infra/service-event-ingestion/lambda/wfm_event_handler/wfm_event_handler.py
Labels: fix
